package Vistas;

import Clases.Cuenta;
import Conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.print.DocFlavor;
import javax.swing.JOptionPane;

public class Consignar extends javax.swing.JFrame {
    
    private double saldo;
    private String cedula;
    
    
     public void setSaldo(int saldo){
        this.saldo = saldo;
        txtValorActual.setText(String.valueOf(saldo));
        
    }
    
    public void obtenerCedula (String cedula) {
        this.cedula = cedula;
        txtCedula.setText(cedula);
    }
    
    
public Consignar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtValorConsignar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtValorActual = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("CONSIGNAR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabel2.setText("Valor a Consignar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 160, 30));

        txtValorConsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorConsignarActionPerformed(evt);
            }
        });
        jPanel1.add(txtValorConsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 210, 40));

        jButton1.setText("Consignar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 150, 50));

        jLabel3.setText("Valor Actual ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txtValorActual.setText("jLabel4");
        jPanel1.add(txtValorActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 190, 50));

        jLabel4.setText("Cuenta");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 110, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorConsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorConsignarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorConsignarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String montoStr = txtValorConsignar.getText();
        double monto = Double.parseDouble(montoStr);

        String cedula = txtCedula.getText();

        if (monto >0) {
            // Actualizar el saldo en la base de datos
            Conexion con = new Conexion();
            Connection connection = null;
            PreparedStatement statement = null;

            try {
                // Establecer la conexión con la base de datos
                connection = con.getConnection();

                // Actualizar el saldo en la tabla 'cuenta'
                String sql = "UPDATE cuenta SET saldo = saldo + ? WHERE cedula = ?";
                statement = connection.prepareStatement(sql);
                statement.setDouble(1, monto);
                statement.setString(2, cedula);
                statement.executeUpdate();

                // Actualizar el saldo en el objeto actual
                saldo -= monto;
            } catch (SQLException e) {
                // Manejar cualquier excepción de SQL
                e.printStackTrace();
            }
        } else {
            // Saldo insuficiente para realizar el retiro
            System.out.println("Por favor verifique el monto a consignar");
        }
        
        JOptionPane.showMessageDialog(this, "Consignaciòn exitosa");
        
        Login login = new Login();
        login.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consignar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consignar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consignar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consignar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consignar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtCedula;
    private javax.swing.JLabel txtValorActual;
    private javax.swing.JTextField txtValorConsignar;
    // End of variables declaration//GEN-END:variables
}
