/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Cuenta;
import Conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.print.DocFlavor;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class Transferir extends javax.swing.JFrame {
    
    private double saldo;
     private String cedula;
    
    public void setSaldo(int saldo){
        this.saldo = saldo;
        txtValorActual.setText(String.valueOf(saldo));
        
    }
    
    public void obtenerCedula (String cedula) {
        this.cedula = cedula;
        txtCedula.setText(cedula);
    }
    
    
    public Transferir( ){
    initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtValorTransferir = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtValorActual = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCuentaTransferir = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Transferir");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabel2.setText("Valor a Transferir:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 160, 30));

        txtValorTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorTransferirActionPerformed(evt);
            }
        });
        jPanel1.add(txtValorTransferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 210, 40));

        jButton1.setText("Transferir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 150, 50));

        jLabel3.setText("Valor Actual ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txtValorActual.setText("jLabel4");
        jPanel1.add(txtValorActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 190, 50));

        jLabel4.setText("Cuenta");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 110, 20));

        jLabel5.setText("Cuenta a Transferir:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 160, 30));

        txtCuentaTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentaTransferirActionPerformed(evt);
            }
        });
        jPanel1.add(txtCuentaTransferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 210, 40));

        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 50, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorTransferirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorTransferirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String montoStr = txtValorTransferir.getText();
        double monto = Double.parseDouble(montoStr);
        
        String cedula = txtCedula.getText();
        String cuentaTransferir = txtCuentaTransferir.getText();
        
        if (saldo >= monto) {
            // Actualizar el saldo en la base de datos
            Conexion con = new Conexion();
            Connection connection = null;
            PreparedStatement statement = null;

            try {
                // Establecer la conexión con la base de datos
                connection = con.getConnection();

                // Actualizar el saldo en la tabla 'cuenta'
                String sql = "UPDATE cuenta SET saldo = saldo - ? WHERE cedula = ?";
                statement = connection.prepareStatement(sql);
                statement.setDouble(1, monto);
                statement.setString(2, cedula);
                statement.executeUpdate();
                
                
                // Actualizar el saldo en la tabla 'cuenta' para la cuenta de destino
                String sqlDestino = "UPDATE cuenta SET saldo = saldo + ? WHERE cedula = ?";
                statement = connection.prepareStatement(sqlDestino);
                statement.setDouble(1, monto);
                statement.setString(2, cuentaTransferir);
                statement.executeUpdate();

                // Actualizar el saldo en el objeto actual
                saldo -= monto;
                
            } catch (SQLException e) {
                // Manejar cualquier excepción de SQL
                e.printStackTrace();
            } 
        } else {
            // Saldo insuficiente para realizar el retiro
            System.out.println("Saldo insuficiente");
        }        
        
         JOptionPane.showMessageDialog(this, "Transferencia exitosa");
         
        Login login = new Login();
        login.setVisible(true);

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCuentaTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentaTransferirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentaTransferirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           
        ListaFavoritos listaFavoritos = new ListaFavoritos();
        listaFavoritos.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //Cuenta cuenta = new Cuenta (0, "h");
               new Transferir().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtCedula;
    private javax.swing.JTextField txtCuentaTransferir;
    private javax.swing.JLabel txtValorActual;
    private javax.swing.JTextField txtValorTransferir;
    // End of variables declaration//GEN-END:variables
}
